Ext.define("admin.model.UserFieldModel",{
    extend:'Ext.data.Model',
    fields:[
    	{name: 'id',type: 'int'},
        {name:'user.id',type:'int'},
        {name:'user.name',type:'String'},
        {name: 'fieldName',type: 'string'},
        {name: 'dbType',type:'string'},
        {name: 'relation',type:'string'},
        {name: 'text',type:'string'},
        {name:'max',type:'float'},
        {name:'min',type:'float'},
        {name:'maxSize',type:'int'},
        {name:'scale',type:'int'},
        {name:'bitian',type:'boolean'},
        {name:'isMoney',type:'boolean'},
        {name:'weiyi',type:'boolean'},
        {name:'mohu',type:'boolean'},
        {name:'heji',type:'boolean'},
        {name:'must',type:'boolean'},
        {name:'defValue',type:'defValue'},
        {name:'inputType',type:'inputType'},
        {name:'note',type:'string'},
        {name: 'dateFormat',type:'string'},
        {name: 'remark',type:'string'},
        {name:'regex',type:'string'},
        {name: 'module.moduleName',type:'string'},
        {name: 'module.modelId',type:'string'},
        {name: 'module.id',type:'int'},
        {name:'dict.id',type:'int'},
        {name:'dict.text'},
        {name:'dateCreated',type:'date'},
        {name:'lastUpdated',type:'date'},
        {name:'dbTypeName'},
        {name:'pageType',type:'string'},
        {name:'win'}
    ]
});