/**
 * Created by shqv on 2014-6-16.
 */
Ext.define("user.model.ScheduleEventModel",{
    extend:'Ext.data.Model',
    fields:[
        {name: 'EventId',mapping: 'id',type: 'int'},
        {name: 'CalendarId',mapping: 'cid',type: 'int'},
        {name: 'Title',mapping: 'subject',type: 'string'},
        {name: 'StartDate',mapping: 'planStartDate',type: 'date'},
        {name: 'EndDate',mapping: 'planEndDate',type: 'date'},
        {name: 'IsAllDay',mapping: 'ad',type: 'boolean'},
        {name: 'id',type: 'int'},
        {name: 'subject',type: 'string'},
        {name: 'planStartDate',type: 'date'},
        {name: 'planEndDate',type: 'date'},
        {name: 'employee'},
        {name: 'owner'},
        {name: 'customer'},
        {name: 'customerFollow'},
        {name: 'saleChance'},
        {name: 'saleChanceFollow'},
        {name: 'taskState',type: 'int'},
        {name: 'taskDesc',type: 'string'},
        {name: 'relatedType',type: 'int'},
        {name: 'taskSummary',type: 'string'},
        {name: 'deleteFlag',type: 'boolean'},
        {name: 'dateCreated',type: 'date'},
        {name: 'lastUpdated',type: 'date'},
        {name: 'files'},
        {name: 'files.name',type: 'string'},
        {name: 'files1'},
        {name: 'files1.name',type: 'string'},
        {name: 'extend1',type: 'string'},
        {name: 'extend2',type: 'string'},
        {name: 'extend3',type: 'string'},
        {name: 'extend4',type: 'string'},
        {name: 'extend5',type: 'string'},
        {name: 'extend6',type: 'string'},
        {name: 'extend7',type: 'string'},
        {name: 'extend8',type: 'string'},
        {name: 'extend9',type: 'string'},
        {name: 'extend10',type: 'string'},
        {name: 'extend11',type: 'string'},
        {name: 'extend12',type: 'string'},
        {name: 'extend13',type: 'string'},
        {name: 'extend14',type: 'string'},
        {name: 'extend15',type: 'string'},
        {name: 'extend16',type: 'int'},
        {name: 'extend17',type: 'int'},
        {name: 'extend18',type: 'int'},
        {name: 'extend19',type: 'int'},
        {name: 'extend20',type: 'int'},
        {name: 'extend21',type: 'int'},
        {name: 'extend22',type: 'int'},
        {name: 'extend23',type: 'int'},
        {name: 'extend24',type: 'int'},
        {name: 'extend25',type: 'int'},
        {name: 'extend26',type: 'int'},
        {name: 'extend27',type: 'int'},
        {name: 'extend28',type: 'int'},
        {name: 'extend29',type: 'int'},
        {name: 'extend30',type: 'int'},
        {name: 'extend31',type: 'double'},
        {name: 'extend32',type: 'double'},
        {name: 'extend33',type: 'double'},
        {name: 'extend34',type: 'double'},
        {name: 'extend35',type: 'double'},
        {name: 'extend36',type: 'boolean'},
        {name: 'extend37',type: 'boolean'},
        {name: 'extend38',type: 'boolean'},
        {name: 'extend39',type: 'boolean'},
        {name: 'extend40',type: 'boolean'},
        {name: 'extend41',type: 'date'},
        {name: 'extend42',type: 'date'},
        {name: 'extend43',type: 'date'},
        {name: 'extend44',type: 'date'},
        {name: 'extend45',type: 'date'},
        {name: 'extend46',type: 'string'},
        {name: 'extend47',type: 'string'}
    ]
});