/**
 * Created by like on 2015/8/31.
 */
Ext.define("user.model.SfaEventModel",{
    extend:'Ext.data.Model',
    fields:[
        {name: 'id',type:'int'},
        {name: 'user.id',type: 'int'},
        {name: 'user.name',type: 'string'},
        {name: 'employee.id',type: 'int'},
        {name: 'employee.name',type: 'string'},
        {name: 'sfa.id',type: 'int'},
        {name: 'sfa.name',type: 'string'},
        {name:'name',type:'string'},
        {name:'index',type:'int'},
        {name:'dateType',type:'int'},
        {name:'startDate',type:'date'},
        {name:'endDate',type:'date'},
        {name:'dateField'},
        {name:'dateField.id',type:'int'},
        {name:'dateField.text',type:'string'},
        {name:'beforeEnd',type:'int'},
        {name:'diffPeriod',type:'int'},
        {name:'difftime',type:'int'},
        {name:'lastingDays',type:'int'},
        {name:'dateFieldCycle'},
        {name:'dateFieldCycle.id',type:'int'},
        {name:'dateFieldCycle.text',type:'string'},
        {name:'diffPeriodCycle',type:'int'},
        {name:'beforeEndCycle',type:'int'},
        {name:'difftimeCycle',type:'int'},
        {name:'lastingDaysCycle',type:'int'},
        {name:'intervalPeriod',type:'int'},
        {name:'interval',type:'int'},
        {name:'cycleTimes',type:'int'},
        {name:'timeHour',type:'int'},
        {name:'timeMinute',type:'int'},
        {name:'isLunar',type:'boolean'},
        {name:'receiverType',type:'int'},
        {name:'acceptors'},
        {name:'acceptors.name',type:'string'},
        {name:'isNotify',type:'boolean'},
        {name:'notifySubjectTemplate',type:'string'},
        {name:'notifyContentTemplate',type:'string'},
        {name:'isSms',type:'boolean'},
        {name:'smsSubjcetTemplate',type:'string'},
        {name:'smsContentTemplate',type:'string'},
        {name:'isEmail',type:'boolean'},
        {name:'emailSubjectTemplate',type:'string'},
        {name:'emailContentTemplate',type:'string'},
        {name:'remark',type:'string'},
        {name:'dateCreated',type:'date'},
        {name:'lastUpdated',type:'date'}
    ]
});